### ISSUE TITLE
Korean dictionary (fresh) doesn't work properly with electron-hunspell

### ISSUE THREAD

**Issue by XanderEmu** [kwonoj/electron-hunspell#620]
I tried to electron-hunspell with Korean dictionary I've got from https://github.com/spellcheck-ko/hunspell-dict-ko 

The related npm package is outdated (https://www.npmjs.com/package/hunspell-dict-ko) so I grabbed a dictionary from a source.

It didn't work, unfortunately, tho it worked fine with the CLI Hunspell so the dictionary itself seems to be fine. With electron-hunspell, it didn't marked anything unless you used a diacritic.

The dictionary itself looks like it contains every possible Korean and non-diacritic Latin character. Perhaps this was misinterpreted by electron-hunspell.

**Comment by kwonoj** [comment]
I just tried those dict with this repo's example code and it works fine.
![image](https://user-images.githubusercontent.com/1210596/74547009-47b72280-4f00-11ea-8ba6-d6e1ae46b53b.png) 

side note fyi, I intentionally released `hunspell-dict-ko` with lower version due to https://github.com/spellcheck-ko/hunspell-dict-ko/issues/30 at the moment and given size of aff in new version grows larger than that version there will be more perf penalty need to caution.
